"""add pax_type to umrah_pilgrims

Revision ID: 1d4dc31f0311
Revises: c1a2b3d4e5f6
Create Date: 2026-09-22 12:02:17.630370+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4dc31f0311'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pax', schema=None) as batch_op:
        batch_op.alter_column('pax_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Adult', 'Child', 'Infant', name='pax_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Adult'"))

    with op.batch_alter_table('umrah_pilgrims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pax_type', sa.String(length=10), nullable=False, server_default="Adult"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umrah_pilgrims', schema=None) as batch_op:
        batch_op.drop_column('pax_type')

    with op.batch_alter_table('pax', schema=None) as batch_op:
        batch_op.alter_column('pax_type',
               existing_type=sa.Enum('Adult', 'Child', 'Infant', name='pax_type_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'Adult'"))

    # ### end Alembic commands ###
