"""Add InternalTransfer and Cash/Bank stratification

Revision ID: 3645a186cac0
Revises: 3e16f03c4d96
Create Date: 2026-09-07 11:23:18.787480+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3645a186cac0'
down_revision: Union[str, None] = '3e16f03c4d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS internal_transfers')
    op.create_table('internal_transfers',
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('destination_bank_account', sa.String(length=100), nullable=True, comment='Specific bank (e.g. Meezan Bank)'),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internal_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internal_transfers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_transfers_transfer_date'), ['transfer_date'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=100), nullable=True))
        # Update existing nulls to CASH first (if there are any) before altering to NOT NULL
        batch_op.execute("UPDATE expenses SET payment_source = 'CASH' WHERE payment_source IS NULL")
        batch_op.alter_column('payment_source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CASH', 'BANK', name='payment_source_enum'),
               nullable=False,
               server_default='CASH')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='payment_source_enum'), nullable=False, server_default='CASH'))
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='payment_source_enum'), nullable=False, server_default='BANK'))
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.drop_column('bank_account_name')
        batch_op.drop_column('payment_source')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('bank_account_name')
        batch_op.drop_column('payment_source')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('payment_source',
               existing_type=sa.Enum('CASH', 'BANK', name='payment_source_enum'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('bank_account_name')

    with op.batch_alter_table('internal_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internal_transfers_transfer_date'))
        batch_op.drop_index(batch_op.f('ix_internal_transfers_is_deleted'))

    op.drop_table('internal_transfers')
    # ### end Alembic commands ###
