"""Add makkah and madina helpline phone and whatsapp fields to vendor

Revision ID: 3e16f03c4d96
Revises: a9f610ea9d7f
Create Date: 2026-09-05 10:57:34.077941+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e16f03c4d96'
down_revision: Union[str, None] = 'a9f610ea9d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_customers_customer_code'))
        batch_op.create_index(batch_op.f('ix_customers_customer_code'), ['customer_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('makkah_helpline_phone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('makkah_helpline_whatsapp', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('madinah_helpline_phone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('madinah_helpline_whatsapp', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('madinah_helpline_whatsapp')
        batch_op.drop_column('madinah_helpline_phone')
        batch_op.drop_column('makkah_helpline_whatsapp')
        batch_op.drop_column('makkah_helpline_phone')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_code'))
        batch_op.create_index(batch_op.f('ix_customers_customer_code'), ['customer_code'], unique=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
