"""Add voucher fields

Revision ID: 7297bfc821a7
Revises: 0001
Create Date: 2026-07-22 19:25:31.547177+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7297bfc821a7'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('arrival_time', sa.String(length=10), nullable=True))

    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hn_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hotel_name_override', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('reservation_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_route', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('tn_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vehicle_type_override', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('booking_ref', sa.String(length=100), nullable=True))

    with op.batch_alter_table('umrah_pilgrims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_no', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umrah_pilgrims', schema=None) as batch_op:
        batch_op.drop_column('group_no')

    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.drop_column('booking_ref')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('vehicle_type_override')
        batch_op.drop_column('tn_number')
        batch_op.drop_column('service_route')

    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.drop_column('reservation_name')
        batch_op.drop_column('hotel_name_override')
        batch_op.drop_column('hn_number')

    with op.batch_alter_table('flight_bookings', schema=None) as batch_op:
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('flight_number')

    # ### end Alembic commands ###
