"""add_package_id_to_bookings

Revision ID: a9f610ea9d7f
Revises: 5a5d56261c8c
Create Date: 2026-07-28 13:59:15.576681+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f610ea9d7f'
down_revision: Union[str, None] = '5a5d56261c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
