"""Add Umrah base purchase and profit columns

Revision ID: aeeb865235df
Revises: b34c5ee11c90
Create Date: 2026-07-26 11:41:16.010117+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeeb865235df'
down_revision: Union[str, None] = 'b34c5ee11c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_umrah_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_purchase_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('base_profit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_umrah_bookings', schema=None) as batch_op:
        batch_op.drop_column('base_profit')
        batch_op.drop_column('base_purchase_cost')

    # ### end Alembic commands ###
