"""Add financial tracking

Revision ID: b34c5ee11c90
Revises: 7297bfc821a7
Create Date: 2026-07-23 09:16:18.940229+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34c5ee11c90'
down_revision: Union[str, None] = '7297bfc821a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('sales_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('sales_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('sales_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('visa_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('sales_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_applications', schema=None) as batch_op:
        batch_op.drop_column('sales_price')
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.drop_column('profit')
        batch_op.drop_column('sales_price')
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.drop_column('sales_price')
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('flight_bookings', schema=None) as batch_op:
        batch_op.drop_column('sales_price')
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
